[2022-08-29 18:41:57,545] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-29 18:41:57,567] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-29 18:41:57,568] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 18:41:57,571] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-08-29 18:41:57,572] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 18:41:57,608] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): entry_task2> on 2021-01-10 06:00:00+00:00
[2022-08-29 18:41:57,619] {standard_task_runner.py:52} INFO - Started process 5263 to run task
[2022-08-29 18:41:57,626] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data_v3', 'entry_task2', 'scheduled__2021-01-10T06:00:00+00:00', '--job-id', '1653', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmp91hnkjbd', '--error-file', '/tmp/tmpaq9x7ai5']
[2022-08-29 18:41:57,629] {standard_task_runner.py:77} INFO - Job 1653: Subtask entry_task2
[2022-08-29 18:41:57,928] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data_v3.entry_task2 scheduled__2021-01-10T06:00:00+00:00 [running]> on host f153c6531160
[2022-08-29 18:41:58,190] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data_v3
AIRFLOW_CTX_TASK_ID=entry_task2
AIRFLOW_CTX_EXECUTION_DATE=2021-01-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-10T06:00:00+00:00
[2022-08-29 18:41:58,195] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-29 18:41:58,198] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "None"']
[2022-08-29 18:41:58,247] {subprocess.py:85} INFO - Output:
[2022-08-29 18:41:58,260] {subprocess.py:89} INFO - None
[2022-08-29 18:41:58,264] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-29 18:41:58,344] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=h1b_lca_data_v3, task_id=entry_task2, execution_date=20210110T060000, start_date=20220829T184157, end_date=20220829T184158
[2022-08-29 18:41:58,420] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-29 18:41:58,524] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
