[2022-08-29 19:26:06,995] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v4.entry_task2 scheduled__2022-01-10T06:00:00+00:00 [queued]>
[2022-08-29 19:26:07,033] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data_v4.entry_task2 scheduled__2022-01-10T06:00:00+00:00 [queued]>
[2022-08-29 19:26:07,034] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 19:26:07,037] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-08-29 19:26:07,038] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 19:26:07,076] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): entry_task2> on 2022-01-10 06:00:00+00:00
[2022-08-29 19:26:07,107] {standard_task_runner.py:52} INFO - Started process 7440 to run task
[2022-08-29 19:26:07,135] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data_v4', 'entry_task2', 'scheduled__2022-01-10T06:00:00+00:00', '--job-id', '1737', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmpfr1sbi1d', '--error-file', '/tmp/tmpf28kgkwm']
[2022-08-29 19:26:07,138] {standard_task_runner.py:77} INFO - Job 1737: Subtask entry_task2
[2022-08-29 19:26:07,412] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data_v4.entry_task2 scheduled__2022-01-10T06:00:00+00:00 [running]> on host f153c6531160
[2022-08-29 19:26:07,672] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data_v4
AIRFLOW_CTX_TASK_ID=entry_task2
AIRFLOW_CTX_EXECUTION_DATE=2022-01-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-10T06:00:00+00:00
[2022-08-29 19:26:07,704] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-29 19:26:07,725] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "1"']
[2022-08-29 19:26:07,782] {subprocess.py:85} INFO - Output:
[2022-08-29 19:26:07,791] {subprocess.py:89} INFO - 1
[2022-08-29 19:26:07,793] {subprocess.py:93} INFO - Command exited with return code 0
[2022-08-29 19:26:07,879] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=h1b_lca_data_v4, task_id=entry_task2, execution_date=20220110T060000, start_date=20220829T192606, end_date=20220829T192607
[2022-08-29 19:26:07,965] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-29 19:26:08,081] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
